// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

@import Foundation;

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FVPPlatformVideoViewCreationParams;
@class FVPCreationOptions;
@class FVPCacheOptionsMessage;
@class FVPBufferOptionsMessage;
@class FVPLoggerOptionsMessage;
@class FVPTexturePlayerIds;
@class FVPMediaSelectionAudioTrackData;

/// Information passed to the platform view creation.
@interface FVPPlatformVideoViewCreationParams : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithPlayerId:(NSInteger )playerId;
@property(nonatomic, assign) NSInteger  playerId;
@end

@interface FVPCreationOptions : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAsset:(nullable NSString *)asset
    uri:(nullable NSString *)uri
    packageName:(nullable NSString *)packageName
    formatHint:(nullable NSString *)formatHint
    httpHeaders:(NSDictionary<NSString *, NSString *> *)httpHeaders
    bufferOptions:(nullable FVPBufferOptionsMessage *)bufferOptions
    loggerOptions:(nullable FVPLoggerOptionsMessage *)loggerOptions;
@property(nonatomic, copy, nullable) NSString * asset;
@property(nonatomic, copy, nullable) NSString * uri;
@property(nonatomic, copy, nullable) NSString * packageName;
@property(nonatomic, copy, nullable) NSString * formatHint;
@property(nonatomic, copy) NSDictionary<NSString *, NSString *> * httpHeaders;
@property(nonatomic, strong, nullable) FVPBufferOptionsMessage * bufferOptions;
@property(nonatomic, strong, nullable) FVPLoggerOptionsMessage * loggerOptions;
@end

@interface FVPCacheOptionsMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithEnableCache:(BOOL )enableCache
    cacheDirectory:(NSString *)cacheDirectory
    maxCacheBytes:(NSInteger )maxCacheBytes
    maxFileBytes:(NSInteger )maxFileBytes;
@property(nonatomic, assign) BOOL  enableCache;
@property(nonatomic, copy) NSString * cacheDirectory;
@property(nonatomic, assign) NSInteger  maxCacheBytes;
@property(nonatomic, assign) NSInteger  maxFileBytes;
@end

@interface FVPBufferOptionsMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithPreferredForwardBufferDuration:(NSInteger )preferredForwardBufferDuration
    canUseNetworkResourcesForLiveStreamingWhilePaused:(BOOL )canUseNetworkResourcesForLiveStreamingWhilePaused
    automaticallyWaitsToMinimizeStalling:(BOOL )automaticallyWaitsToMinimizeStalling;
@property(nonatomic, assign) NSInteger  preferredForwardBufferDuration;
@property(nonatomic, assign) BOOL  canUseNetworkResourcesForLiveStreamingWhilePaused;
@property(nonatomic, assign) BOOL  automaticallyWaitsToMinimizeStalling;
@end

@interface FVPLoggerOptionsMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithEnableTransferListenerLogs:(BOOL )enableTransferListenerLogs
    enableBandwidthListenerLogs:(BOOL )enableBandwidthListenerLogs
    enableAdaptiveTrackSelectionLogs:(BOOL )enableAdaptiveTrackSelectionLogs
    enableCacheDataSourceLogs:(BOOL )enableCacheDataSourceLogs;
@property(nonatomic, assign) BOOL  enableTransferListenerLogs;
@property(nonatomic, assign) BOOL  enableBandwidthListenerLogs;
@property(nonatomic, assign) BOOL  enableAdaptiveTrackSelectionLogs;
@property(nonatomic, assign) BOOL  enableCacheDataSourceLogs;
@end

@interface FVPTexturePlayerIds : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithPlayerId:(NSInteger )playerId
    textureId:(NSInteger )textureId;
@property(nonatomic, assign) NSInteger  playerId;
@property(nonatomic, assign) NSInteger  textureId;
@end

/// Raw audio track data from AVMediaSelectionOption (for HLS streams).
@interface FVPMediaSelectionAudioTrackData : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithIndex:(NSInteger )index
    displayName:(nullable NSString *)displayName
    languageCode:(nullable NSString *)languageCode
    isSelected:(BOOL )isSelected
    commonMetadataTitle:(nullable NSString *)commonMetadataTitle;
@property(nonatomic, assign) NSInteger  index;
@property(nonatomic, copy, nullable) NSString * displayName;
@property(nonatomic, copy, nullable) NSString * languageCode;
@property(nonatomic, assign) BOOL  isSelected;
@property(nonatomic, copy, nullable) NSString * commonMetadataTitle;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *FVPGetMessagesCodec(void);

@protocol FVPAVFoundationVideoPlayerApi
- (void)initialize:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)createPlatformViewPlayerWithOptions:(FVPCreationOptions *)params error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable FVPTexturePlayerIds *)createTexturePlayerWithOptions:(FVPCreationOptions *)creationOptions error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setMixWithOthers:(BOOL)mixWithOthers error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setCacheOptions:(FVPCacheOptionsMessage *)msg error:(FlutterError *_Nullable *_Nonnull)error;
- (nullable NSString *)fileURLForAssetWithName:(NSString *)asset package:(nullable NSString *)package error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpFVPAVFoundationVideoPlayerApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FVPAVFoundationVideoPlayerApi> *_Nullable api);

extern void SetUpFVPAVFoundationVideoPlayerApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FVPAVFoundationVideoPlayerApi> *_Nullable api, NSString *messageChannelSuffix);


@protocol FVPVideoPlayerInstanceApi
- (void)setLooping:(BOOL)looping error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setVolume:(double)volume error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setPlaybackSpeed:(double)speed error:(FlutterError *_Nullable *_Nonnull)error;
- (void)playWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)position:(FlutterError *_Nullable *_Nonnull)error;
- (void)seekTo:(NSInteger)position completion:(void (^)(FlutterError *_Nullable))completion;
- (void)pauseWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)disposeWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<FVPMediaSelectionAudioTrackData *> *)getAudioTracks:(FlutterError *_Nullable *_Nonnull)error;
- (void)selectAudioTrackAtIndex:(NSInteger)trackIndex error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpFVPVideoPlayerInstanceApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FVPVideoPlayerInstanceApi> *_Nullable api);

extern void SetUpFVPVideoPlayerInstanceApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FVPVideoPlayerInstanceApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
