// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "./include/video_player_avfoundation/messages.g.h"

#if TARGET_OS_OSX
@import FlutterMacOS;
#else
@import Flutter;
#endif

static BOOL __attribute__((unused)) FLTPigeonDeepEquals(id _Nullable a, id _Nullable b) {
  if (a == b) {
    return YES;
  }
  if (a == nil) {
    return b == [NSNull null];
  }
  if (b == nil) {
    return a == [NSNull null];
  }
  if ([a isKindOfClass:[NSNumber class]] && [b isKindOfClass:[NSNumber class]]) {
    return [a isEqual:b] || (isnan([(NSNumber *)a doubleValue]) && isnan([(NSNumber *)b doubleValue]));
  }
  if ([a isKindOfClass:[NSArray class]] && [b isKindOfClass:[NSArray class]]) {
    NSArray *arrayA = (NSArray *)a;
    NSArray *arrayB = (NSArray *)b;
    if (arrayA.count != arrayB.count) {
      return NO;
    }
    for (NSUInteger i = 0; i < arrayA.count; i++) {
      if (!FLTPigeonDeepEquals(arrayA[i], arrayB[i])) {
        return NO;
      }
    }
    return YES;
  }
  if ([a isKindOfClass:[NSDictionary class]] && [b isKindOfClass:[NSDictionary class]]) {
    NSDictionary *dictA = (NSDictionary *)a;
    NSDictionary *dictB = (NSDictionary *)b;
    if (dictA.count != dictB.count) {
      return NO;
    }
    for (id keyA in dictA) {
      id valueA = dictA[keyA];
      BOOL found = NO;
      for (id keyB in dictB) {
        if (FLTPigeonDeepEquals(keyA, keyB)) {
          id valueB = dictB[keyB];
          if (FLTPigeonDeepEquals(valueA, valueB)) {
            found = YES;
            break;
          } else {
            return NO;
          }
        }
      }
      if (!found) {
        return NO;
      }
    }
    return YES;
  }
  return [a isEqual:b];
}

static NSUInteger __attribute__((unused)) FLTPigeonDeepHash(id _Nullable value) {
  if (value == nil || value == (id)[NSNull null]) {
    return 0;
  }
  if ([value isKindOfClass:[NSNumber class]]) {
    NSNumber *n = (NSNumber *)value;
    double d = n.doubleValue;
    if (isnan(d)) {
      // Normalize NaN to a consistent hash.
      return (NSUInteger)0x7FF8000000000000;
    }
    if (d == 0.0) {
      // Normalize -0.0 to 0.0 so they have the same hash code.
      d = 0.0;
    }
    return @(d).hash;
  }
  if ([value isKindOfClass:[NSArray class]]) {
    NSUInteger result = 1;
    for (id item in (NSArray *)value) {
      result = result * 31 + FLTPigeonDeepHash(item);
    }
    return result;
  }
  if ([value isKindOfClass:[NSDictionary class]]) {
    NSUInteger result = 0;
    NSDictionary *dict = (NSDictionary *)value;
    for (id key in dict) {
      result += ((FLTPigeonDeepHash(key) * 31) ^ FLTPigeonDeepHash(dict[key]));
    }
    return result;
  }
  return [value hash];
}

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface FVPPlatformVideoViewCreationParams ()
+ (FVPPlatformVideoViewCreationParams *)fromList:(NSArray<id> *)list;
+ (nullable FVPPlatformVideoViewCreationParams *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FVPCreationOptions ()
+ (FVPCreationOptions *)fromList:(NSArray<id> *)list;
+ (nullable FVPCreationOptions *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FVPCacheOptionsMessage ()
+ (FVPCacheOptionsMessage *)fromList:(NSArray<id> *)list;
+ (nullable FVPCacheOptionsMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FVPBufferOptionsMessage ()
+ (FVPBufferOptionsMessage *)fromList:(NSArray<id> *)list;
+ (nullable FVPBufferOptionsMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FVPLoggerOptionsMessage ()
+ (FVPLoggerOptionsMessage *)fromList:(NSArray<id> *)list;
+ (nullable FVPLoggerOptionsMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FVPTexturePlayerIds ()
+ (FVPTexturePlayerIds *)fromList:(NSArray<id> *)list;
+ (nullable FVPTexturePlayerIds *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FVPMediaSelectionAudioTrackData ()
+ (FVPMediaSelectionAudioTrackData *)fromList:(NSArray<id> *)list;
+ (nullable FVPMediaSelectionAudioTrackData *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation FVPPlatformVideoViewCreationParams
+ (instancetype)makeWithPlayerId:(NSInteger )playerId {
  FVPPlatformVideoViewCreationParams* pigeonResult = [[FVPPlatformVideoViewCreationParams alloc] init];
  pigeonResult.playerId = playerId;
  return pigeonResult;
}
+ (FVPPlatformVideoViewCreationParams *)fromList:(NSArray<id> *)list {
  FVPPlatformVideoViewCreationParams *pigeonResult = [[FVPPlatformVideoViewCreationParams alloc] init];
  pigeonResult.playerId = [GetNullableObjectAtIndex(list, 0) integerValue];
  return pigeonResult;
}
+ (nullable FVPPlatformVideoViewCreationParams *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FVPPlatformVideoViewCreationParams fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.playerId),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  FVPPlatformVideoViewCreationParams *other = (FVPPlatformVideoViewCreationParams *)object;
  return self.playerId == other.playerId;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.playerId).hash;
  return result;
}
@end

@implementation FVPCreationOptions
+ (instancetype)makeWithAsset:(nullable NSString *)asset
    uri:(nullable NSString *)uri
    packageName:(nullable NSString *)packageName
    formatHint:(nullable NSString *)formatHint
    httpHeaders:(NSDictionary<NSString *, NSString *> *)httpHeaders
    bufferOptions:(nullable FVPBufferOptionsMessage *)bufferOptions
    loggerOptions:(nullable FVPLoggerOptionsMessage *)loggerOptions {
  FVPCreationOptions* pigeonResult = [[FVPCreationOptions alloc] init];
  pigeonResult.asset = asset;
  pigeonResult.uri = uri;
  pigeonResult.packageName = packageName;
  pigeonResult.formatHint = formatHint;
  pigeonResult.httpHeaders = httpHeaders;
  pigeonResult.bufferOptions = bufferOptions;
  pigeonResult.loggerOptions = loggerOptions;
  return pigeonResult;
}
+ (FVPCreationOptions *)fromList:(NSArray<id> *)list {
  FVPCreationOptions *pigeonResult = [[FVPCreationOptions alloc] init];
  pigeonResult.asset = GetNullableObjectAtIndex(list, 0);
  pigeonResult.uri = GetNullableObjectAtIndex(list, 1);
  pigeonResult.packageName = GetNullableObjectAtIndex(list, 2);
  pigeonResult.formatHint = GetNullableObjectAtIndex(list, 3);
  pigeonResult.httpHeaders = GetNullableObjectAtIndex(list, 4);
  pigeonResult.bufferOptions = GetNullableObjectAtIndex(list, 5);
  pigeonResult.loggerOptions = GetNullableObjectAtIndex(list, 6);
  return pigeonResult;
}
+ (nullable FVPCreationOptions *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FVPCreationOptions fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.asset ?: [NSNull null],
    self.uri ?: [NSNull null],
    self.packageName ?: [NSNull null],
    self.formatHint ?: [NSNull null],
    self.httpHeaders ?: [NSNull null],
    self.bufferOptions ?: [NSNull null],
    self.loggerOptions ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  FVPCreationOptions *other = (FVPCreationOptions *)object;
  return FLTPigeonDeepEquals(self.asset, other.asset) && FLTPigeonDeepEquals(self.uri, other.uri) && FLTPigeonDeepEquals(self.packageName, other.packageName) && FLTPigeonDeepEquals(self.formatHint, other.formatHint) && FLTPigeonDeepEquals(self.httpHeaders, other.httpHeaders) && FLTPigeonDeepEquals(self.bufferOptions, other.bufferOptions) && FLTPigeonDeepEquals(self.loggerOptions, other.loggerOptions);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.asset);
  result = result * 31 + FLTPigeonDeepHash(self.uri);
  result = result * 31 + FLTPigeonDeepHash(self.packageName);
  result = result * 31 + FLTPigeonDeepHash(self.formatHint);
  result = result * 31 + FLTPigeonDeepHash(self.httpHeaders);
  result = result * 31 + FLTPigeonDeepHash(self.bufferOptions);
  result = result * 31 + FLTPigeonDeepHash(self.loggerOptions);
  return result;
}
@end

@implementation FVPCacheOptionsMessage
+ (instancetype)makeWithEnableCache:(BOOL )enableCache
    cacheDirectory:(NSString *)cacheDirectory
    maxCacheBytes:(NSInteger )maxCacheBytes
    maxFileBytes:(NSInteger )maxFileBytes {
  FVPCacheOptionsMessage* pigeonResult = [[FVPCacheOptionsMessage alloc] init];
  pigeonResult.enableCache = enableCache;
  pigeonResult.cacheDirectory = cacheDirectory;
  pigeonResult.maxCacheBytes = maxCacheBytes;
  pigeonResult.maxFileBytes = maxFileBytes;
  return pigeonResult;
}
+ (FVPCacheOptionsMessage *)fromList:(NSArray<id> *)list {
  FVPCacheOptionsMessage *pigeonResult = [[FVPCacheOptionsMessage alloc] init];
  pigeonResult.enableCache = [GetNullableObjectAtIndex(list, 0) boolValue];
  pigeonResult.cacheDirectory = GetNullableObjectAtIndex(list, 1);
  pigeonResult.maxCacheBytes = [GetNullableObjectAtIndex(list, 2) integerValue];
  pigeonResult.maxFileBytes = [GetNullableObjectAtIndex(list, 3) integerValue];
  return pigeonResult;
}
+ (nullable FVPCacheOptionsMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FVPCacheOptionsMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.enableCache),
    self.cacheDirectory ?: [NSNull null],
    @(self.maxCacheBytes),
    @(self.maxFileBytes),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  FVPCacheOptionsMessage *other = (FVPCacheOptionsMessage *)object;
  return self.enableCache == other.enableCache && FLTPigeonDeepEquals(self.cacheDirectory, other.cacheDirectory) && self.maxCacheBytes == other.maxCacheBytes && self.maxFileBytes == other.maxFileBytes;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.enableCache).hash;
  result = result * 31 + FLTPigeonDeepHash(self.cacheDirectory);
  result = result * 31 + @(self.maxCacheBytes).hash;
  result = result * 31 + @(self.maxFileBytes).hash;
  return result;
}
@end

@implementation FVPBufferOptionsMessage
+ (instancetype)makeWithPreferredForwardBufferDuration:(NSInteger )preferredForwardBufferDuration
    canUseNetworkResourcesForLiveStreamingWhilePaused:(BOOL )canUseNetworkResourcesForLiveStreamingWhilePaused
    automaticallyWaitsToMinimizeStalling:(BOOL )automaticallyWaitsToMinimizeStalling {
  FVPBufferOptionsMessage* pigeonResult = [[FVPBufferOptionsMessage alloc] init];
  pigeonResult.preferredForwardBufferDuration = preferredForwardBufferDuration;
  pigeonResult.canUseNetworkResourcesForLiveStreamingWhilePaused = canUseNetworkResourcesForLiveStreamingWhilePaused;
  pigeonResult.automaticallyWaitsToMinimizeStalling = automaticallyWaitsToMinimizeStalling;
  return pigeonResult;
}
+ (FVPBufferOptionsMessage *)fromList:(NSArray<id> *)list {
  FVPBufferOptionsMessage *pigeonResult = [[FVPBufferOptionsMessage alloc] init];
  pigeonResult.preferredForwardBufferDuration = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.canUseNetworkResourcesForLiveStreamingWhilePaused = [GetNullableObjectAtIndex(list, 1) boolValue];
  pigeonResult.automaticallyWaitsToMinimizeStalling = [GetNullableObjectAtIndex(list, 2) boolValue];
  return pigeonResult;
}
+ (nullable FVPBufferOptionsMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FVPBufferOptionsMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.preferredForwardBufferDuration),
    @(self.canUseNetworkResourcesForLiveStreamingWhilePaused),
    @(self.automaticallyWaitsToMinimizeStalling),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  FVPBufferOptionsMessage *other = (FVPBufferOptionsMessage *)object;
  return self.preferredForwardBufferDuration == other.preferredForwardBufferDuration && self.canUseNetworkResourcesForLiveStreamingWhilePaused == other.canUseNetworkResourcesForLiveStreamingWhilePaused && self.automaticallyWaitsToMinimizeStalling == other.automaticallyWaitsToMinimizeStalling;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.preferredForwardBufferDuration).hash;
  result = result * 31 + @(self.canUseNetworkResourcesForLiveStreamingWhilePaused).hash;
  result = result * 31 + @(self.automaticallyWaitsToMinimizeStalling).hash;
  return result;
}
@end

@implementation FVPLoggerOptionsMessage
+ (instancetype)makeWithEnableTransferListenerLogs:(BOOL )enableTransferListenerLogs
    enableBandwidthListenerLogs:(BOOL )enableBandwidthListenerLogs
    enableAdaptiveTrackSelectionLogs:(BOOL )enableAdaptiveTrackSelectionLogs
    enableCacheDataSourceLogs:(BOOL )enableCacheDataSourceLogs {
  FVPLoggerOptionsMessage* pigeonResult = [[FVPLoggerOptionsMessage alloc] init];
  pigeonResult.enableTransferListenerLogs = enableTransferListenerLogs;
  pigeonResult.enableBandwidthListenerLogs = enableBandwidthListenerLogs;
  pigeonResult.enableAdaptiveTrackSelectionLogs = enableAdaptiveTrackSelectionLogs;
  pigeonResult.enableCacheDataSourceLogs = enableCacheDataSourceLogs;
  return pigeonResult;
}
+ (FVPLoggerOptionsMessage *)fromList:(NSArray<id> *)list {
  FVPLoggerOptionsMessage *pigeonResult = [[FVPLoggerOptionsMessage alloc] init];
  pigeonResult.enableTransferListenerLogs = [GetNullableObjectAtIndex(list, 0) boolValue];
  pigeonResult.enableBandwidthListenerLogs = [GetNullableObjectAtIndex(list, 1) boolValue];
  pigeonResult.enableAdaptiveTrackSelectionLogs = [GetNullableObjectAtIndex(list, 2) boolValue];
  pigeonResult.enableCacheDataSourceLogs = [GetNullableObjectAtIndex(list, 3) boolValue];
  return pigeonResult;
}
+ (nullable FVPLoggerOptionsMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FVPLoggerOptionsMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.enableTransferListenerLogs),
    @(self.enableBandwidthListenerLogs),
    @(self.enableAdaptiveTrackSelectionLogs),
    @(self.enableCacheDataSourceLogs),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  FVPLoggerOptionsMessage *other = (FVPLoggerOptionsMessage *)object;
  return self.enableTransferListenerLogs == other.enableTransferListenerLogs && self.enableBandwidthListenerLogs == other.enableBandwidthListenerLogs && self.enableAdaptiveTrackSelectionLogs == other.enableAdaptiveTrackSelectionLogs && self.enableCacheDataSourceLogs == other.enableCacheDataSourceLogs;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.enableTransferListenerLogs).hash;
  result = result * 31 + @(self.enableBandwidthListenerLogs).hash;
  result = result * 31 + @(self.enableAdaptiveTrackSelectionLogs).hash;
  result = result * 31 + @(self.enableCacheDataSourceLogs).hash;
  return result;
}
@end

@implementation FVPTexturePlayerIds
+ (instancetype)makeWithPlayerId:(NSInteger )playerId
    textureId:(NSInteger )textureId {
  FVPTexturePlayerIds* pigeonResult = [[FVPTexturePlayerIds alloc] init];
  pigeonResult.playerId = playerId;
  pigeonResult.textureId = textureId;
  return pigeonResult;
}
+ (FVPTexturePlayerIds *)fromList:(NSArray<id> *)list {
  FVPTexturePlayerIds *pigeonResult = [[FVPTexturePlayerIds alloc] init];
  pigeonResult.playerId = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.textureId = [GetNullableObjectAtIndex(list, 1) integerValue];
  return pigeonResult;
}
+ (nullable FVPTexturePlayerIds *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FVPTexturePlayerIds fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.playerId),
    @(self.textureId),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  FVPTexturePlayerIds *other = (FVPTexturePlayerIds *)object;
  return self.playerId == other.playerId && self.textureId == other.textureId;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.playerId).hash;
  result = result * 31 + @(self.textureId).hash;
  return result;
}
@end

@implementation FVPMediaSelectionAudioTrackData
+ (instancetype)makeWithIndex:(NSInteger )index
    displayName:(nullable NSString *)displayName
    languageCode:(nullable NSString *)languageCode
    isSelected:(BOOL )isSelected
    commonMetadataTitle:(nullable NSString *)commonMetadataTitle {
  FVPMediaSelectionAudioTrackData* pigeonResult = [[FVPMediaSelectionAudioTrackData alloc] init];
  pigeonResult.index = index;
  pigeonResult.displayName = displayName;
  pigeonResult.languageCode = languageCode;
  pigeonResult.isSelected = isSelected;
  pigeonResult.commonMetadataTitle = commonMetadataTitle;
  return pigeonResult;
}
+ (FVPMediaSelectionAudioTrackData *)fromList:(NSArray<id> *)list {
  FVPMediaSelectionAudioTrackData *pigeonResult = [[FVPMediaSelectionAudioTrackData alloc] init];
  pigeonResult.index = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.displayName = GetNullableObjectAtIndex(list, 1);
  pigeonResult.languageCode = GetNullableObjectAtIndex(list, 2);
  pigeonResult.isSelected = [GetNullableObjectAtIndex(list, 3) boolValue];
  pigeonResult.commonMetadataTitle = GetNullableObjectAtIndex(list, 4);
  return pigeonResult;
}
+ (nullable FVPMediaSelectionAudioTrackData *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FVPMediaSelectionAudioTrackData fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.index),
    self.displayName ?: [NSNull null],
    self.languageCode ?: [NSNull null],
    @(self.isSelected),
    self.commonMetadataTitle ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  FVPMediaSelectionAudioTrackData *other = (FVPMediaSelectionAudioTrackData *)object;
  return self.index == other.index && FLTPigeonDeepEquals(self.displayName, other.displayName) && FLTPigeonDeepEquals(self.languageCode, other.languageCode) && self.isSelected == other.isSelected && FLTPigeonDeepEquals(self.commonMetadataTitle, other.commonMetadataTitle);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.index).hash;
  result = result * 31 + FLTPigeonDeepHash(self.displayName);
  result = result * 31 + FLTPigeonDeepHash(self.languageCode);
  result = result * 31 + @(self.isSelected).hash;
  result = result * 31 + FLTPigeonDeepHash(self.commonMetadataTitle);
  return result;
}
@end

@interface FVPMessagesPigeonCodecReader : FlutterStandardReader
@end
@implementation FVPMessagesPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: 
      return [FVPPlatformVideoViewCreationParams fromList:[self readValue]];
    case 130: 
      return [FVPCreationOptions fromList:[self readValue]];
    case 131: 
      return [FVPCacheOptionsMessage fromList:[self readValue]];
    case 132: 
      return [FVPBufferOptionsMessage fromList:[self readValue]];
    case 133: 
      return [FVPLoggerOptionsMessage fromList:[self readValue]];
    case 134: 
      return [FVPTexturePlayerIds fromList:[self readValue]];
    case 135: 
      return [FVPMediaSelectionAudioTrackData fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface FVPMessagesPigeonCodecWriter : FlutterStandardWriter
@end
@implementation FVPMessagesPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[FVPPlatformVideoViewCreationParams class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FVPCreationOptions class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FVPCacheOptionsMessage class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FVPBufferOptionsMessage class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FVPLoggerOptionsMessage class]]) {
    [self writeByte:133];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FVPTexturePlayerIds class]]) {
    [self writeByte:134];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FVPMediaSelectionAudioTrackData class]]) {
    [self writeByte:135];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface FVPMessagesPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FVPMessagesPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FVPMessagesPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FVPMessagesPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FVPGetMessagesCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    FVPMessagesPigeonCodecReaderWriter *readerWriter = [[FVPMessagesPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpFVPAVFoundationVideoPlayerApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FVPAVFoundationVideoPlayerApi> *api) {
  SetUpFVPAVFoundationVideoPlayerApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpFVPAVFoundationVideoPlayerApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FVPAVFoundationVideoPlayerApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.initialize", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FVPGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(initialize:)], @"FVPAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(initialize:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api initialize:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.createForPlatformView", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FVPGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(createPlatformViewPlayerWithOptions:error:)], @"FVPAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(createPlatformViewPlayerWithOptions:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FVPCreationOptions *arg_params = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSNumber *output = [api createPlatformViewPlayerWithOptions:arg_params error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.createForTextureView", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FVPGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(createTexturePlayerWithOptions:error:)], @"FVPAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(createTexturePlayerWithOptions:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FVPCreationOptions *arg_creationOptions = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        FVPTexturePlayerIds *output = [api createTexturePlayerWithOptions:arg_creationOptions error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.setMixWithOthers", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FVPGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setMixWithOthers:error:)], @"FVPAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(setMixWithOthers:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        BOOL arg_mixWithOthers = [GetNullableObjectAtIndex(args, 0) boolValue];
        FlutterError *error;
        [api setMixWithOthers:arg_mixWithOthers error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.setCacheOptions", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FVPGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setCacheOptions:error:)], @"FVPAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(setCacheOptions:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FVPCacheOptionsMessage *arg_msg = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setCacheOptions:arg_msg error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.preloadIntoCache", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FVPGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(preloadWithURL:segmentCount:httpHeaders:completion:)], @"FVPAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(preloadWithURL:segmentCount:httpHeaders:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_uri = GetNullableObjectAtIndex(args, 0);
        NSInteger arg_segmentCount = [GetNullableObjectAtIndex(args, 1) integerValue];
        NSDictionary<NSString *, NSString *> *arg_httpHeaders = GetNullableObjectAtIndex(args, 2);
        [api preloadWithURL:arg_uri segmentCount:arg_segmentCount httpHeaders:arg_httpHeaders completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.cancelPreload", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FVPGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(cancelPreloadForURL:error:)], @"FVPAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(cancelPreloadForURL:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_uri = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api cancelPreloadForURL:arg_uri error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.getAssetUrl", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FVPGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(fileURLForAssetWithName:package:error:)], @"FVPAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(fileURLForAssetWithName:package:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_asset = GetNullableObjectAtIndex(args, 0);
        NSString *arg_package = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        NSString *output = [api fileURLForAssetWithName:arg_asset package:arg_package error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
void SetUpFVPVideoPlayerInstanceApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FVPVideoPlayerInstanceApi> *api) {
  SetUpFVPVideoPlayerInstanceApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpFVPVideoPlayerInstanceApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FVPVideoPlayerInstanceApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.VideoPlayerInstanceApi.setLooping", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FVPGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setLooping:error:)], @"FVPVideoPlayerInstanceApi api (%@) doesn't respond to @selector(setLooping:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        BOOL arg_looping = [GetNullableObjectAtIndex(args, 0) boolValue];
        FlutterError *error;
        [api setLooping:arg_looping error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.VideoPlayerInstanceApi.setVolume", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FVPGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setVolume:error:)], @"FVPVideoPlayerInstanceApi api (%@) doesn't respond to @selector(setVolume:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        double arg_volume = [GetNullableObjectAtIndex(args, 0) doubleValue];
        FlutterError *error;
        [api setVolume:arg_volume error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.VideoPlayerInstanceApi.setPlaybackSpeed", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FVPGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setPlaybackSpeed:error:)], @"FVPVideoPlayerInstanceApi api (%@) doesn't respond to @selector(setPlaybackSpeed:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        double arg_speed = [GetNullableObjectAtIndex(args, 0) doubleValue];
        FlutterError *error;
        [api setPlaybackSpeed:arg_speed error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.VideoPlayerInstanceApi.play", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FVPGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(playWithError:)], @"FVPVideoPlayerInstanceApi api (%@) doesn't respond to @selector(playWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api playWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.VideoPlayerInstanceApi.getPosition", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FVPGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(position:)], @"FVPVideoPlayerInstanceApi api (%@) doesn't respond to @selector(position:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api position:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.VideoPlayerInstanceApi.seekTo", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FVPGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(seekTo:completion:)], @"FVPVideoPlayerInstanceApi api (%@) doesn't respond to @selector(seekTo:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_position = [GetNullableObjectAtIndex(args, 0) integerValue];
        [api seekTo:arg_position completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.VideoPlayerInstanceApi.pause", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FVPGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(pauseWithError:)], @"FVPVideoPlayerInstanceApi api (%@) doesn't respond to @selector(pauseWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api pauseWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.VideoPlayerInstanceApi.dispose", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FVPGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(disposeWithError:)], @"FVPVideoPlayerInstanceApi api (%@) doesn't respond to @selector(disposeWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api disposeWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.VideoPlayerInstanceApi.getAudioTracks", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FVPGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getAudioTracks:)], @"FVPVideoPlayerInstanceApi api (%@) doesn't respond to @selector(getAudioTracks:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSArray<FVPMediaSelectionAudioTrackData *> *output = [api getAudioTracks:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.VideoPlayerInstanceApi.selectAudioTrack", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FVPGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(selectAudioTrackAtIndex:error:)], @"FVPVideoPlayerInstanceApi api (%@) doesn't respond to @selector(selectAudioTrackAtIndex:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_trackIndex = [GetNullableObjectAtIndex(args, 0) integerValue];
        FlutterError *error;
        [api selectAudioTrackAtIndex:arg_trackIndex error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
